### ISSUE TITLE
Open in Debug Map link

### ISSUE THREAD

**Issue by katpatuka** [Project-OSRM/project-osrm.github.com#12]
Trying to open the "Open in Debug Map" link gives a SSL_ERROR_BAD_CERT_DOMAIN

Details:
 
map.project-osrm.org uses an invalid security certificate.
The certificate is only valid for the following names:
www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com

No problem using HTTP instead of HTTPS.

**Comment by daniel-j-h** [comment]
Closing as duplicate of https://github.com/Project-OSRM/osrm-frontend/issues/253

The frontend really could need some love ..
