### ISSUE TITLE
503 Server Unavailable

### ISSUE THREAD

**Issue by maniac-tech** [Project-OSRM/project-osrm.github.com#14]
A sample curl request failed with 503 server error.

The sample request made using curl is:
`curl 'http://router.project-osrm.org/nearest/v1/driving/13.388860,52.517037?number=3&bearings=0,20'`

**Comment by daniel-j-h** [comment]
Yes the demo server has some problems; we're planning on switching the router to a Mapbox-powered endpoint. In the meantime check this out:

https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server

Closing as known issue - we're working on it.
