### ISSUE TITLE
router.project-osrm.org certificate is invalid since March 2020

### ISSUE THREAD

**Issue by cyril23** [Project-OSRM/project-osrm.github.com#24]
The certificate of `router.project-osrm.org` is invalid since 9th March 2020. Therefore the use of https://map.project-osrm.org/ is not possible anymore because the API cannot be reached.

Example:

https://router.project-osrm.org/route/v1/driving/-77.026863,38.906263;-77.037163,38.907866?overview=false&alternatives=true&steps=true&hints=;

![image](https://user-images.githubusercontent.com/5645872/82044613-f1e44900-96ad-11ea-824d-2559f3eedc8e.png)

![image](https://user-images.githubusercontent.com/5645872/82044582-e6911d80-96ad-11ea-8100-895f353c8c86.png)

![image](https://user-images.githubusercontent.com/5645872/82044396-93b76600-96ad-11ea-974a-9a4df06062a4.png)

![image](https://user-images.githubusercontent.com/5645872/82044502-bcd7f680-96ad-11ea-9246-07f5b8e6d8aa.png)

Please renew the cert.

**Comment by mjjbell** [comment]
Fixed over in Project-OSRM/osrm-backend/#5655
