### ISSUE TITLE
HTTPS issue: Browser claims connection is not safe

### ISSUE THREAD

**Issue by 1Maxnet1** [Project-OSRM/project-osrm.github.com#26]
When I try to connect to https://project-osrm.org/, I get an warning:
![grafik](https://user-images.githubusercontent.com/24827631/116530631-899e6f80-a8de-11eb-82fd-d76941a7ad43.png)

My Setup: Firefox with HTTPSEverywhere and uBlockOrigin installed.

When I click show more information it sais:
"Websites bestätigen ihre Identität mittels Zertifikaten. Firefox vertraut dieser Website nicht, weil das von der Website verwendete Zertifikat nicht für project-osrm.org gilt. Das Zertifikat gilt nur für folgende Namen: *.github.com, github.com"

Translated to english: "Websites confirm their identity using certificates. Firefox does not trust this website because the certificate used by the website is not valid for project-osrm.org. The certificate is valid only for the following names: *.github.com, github.com"

**Comment by mjjbell** [comment]
According to Github this can be fixed with a simple DNS change to the `A` records : https://github.blog/2018-05-01-github-pages-custom-domains-https/

Unfortunately, I don't know who has admin access to `project-osrm.org` DNS records to make this change.

**Comment by mjjbell** [comment]
https://project-osrm.org/ is now working.
