### ISSUE TITLE
Route export from OSRM website

### ISSUE THREAD

**Issue by holgersoft** [Project-OSRM/project-osrm.github.com#3]
It would be nice to have the option to export a route from the OSRM website.  Preferably in GPX format.  I use such tracks to guide offline routing, e.g. with OsmAnd.  The use case is to store some alternative routes before the trip starts and then use the one the fits best.

Apparently there is a way to get a GEOJson file from the command line.  But to download it from a calculated route from the web site is much more convenient.

**Comment by daniel-j-h** [comment]
:+1: we should at least support GeoJSON exports.

GPX support was removed from `osrm-backend` and therefore the frontend can no longer make use of it.

In the current API we're already returning a GeoJSON geometry which we could either export as is or convert to GPX on the fly (Javascript) and transparently for the user.

**Comment by daniel-j-h** [comment]
Tracking in the frontend over at https://github.com/Project-OSRM/osrm-frontend/issues/190 since this repository is only used to serve the frontend's static output via Github Pages.
